services:
  postgres:
    image: postgres:16
    container_name: postgres

    env_file:
      - .env.example
    environment:
      - POSTGRES_USER=${POSTGRES_USER?POSTGRES_USER variable not set}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?POSTGRES_PASSWORD variable not set}
      - POSTGRES_DB=${POSTGRES_DB?POSTGRES_DB variable not set}
      - PGDATA=/var/lib/postgresql/data/pgdata

    volumes:
      - postgres:/data/postgres

    ports:
      - "5432:5432"
    networks:
      - postgres

    restart: unless-stopped

  pgadmin4:
    image: dpage/pgadmin4:8
    container_name: pgadmin

    env_file: 
      - .env.example
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL?PGADMIN_DEFAULT_EMAIL variable is not set}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD?PGADMIN_DEFAULT_PASSWORD variable is not set}

    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "5050:80"
    networks:
      - postgres

    restart: unless-stopped

networks:
  postgres:
    name: "postgres"

volumes:
  postgres:
  pgadmin: