from enum import IntEnum
from http import HTTPStatus


class ErrorCode(IntEnum):
    BAD_REQUEST = HTTPStatus.BAD_REQUEST
    UNAUTHENTICATED = HTTPStatus.UNAUTHORIZED
    UNAUTHORIZED = HTTPStatus.FORBIDDEN
    VALIDATION_ERROR = HTTPStatus.UNPROCESSABLE_ENTITY
    UNHANDLED_SERVER_ERROR = HTTPStatus.INTERNAL_SERVER_ERROR

    USER_NOT_FOUND = 40001
